### ISSUE TITLE
Handling Categorical Variables

### ISSUE THREAD

**Issue by ElliottP-13** [cullingsj/Machine_Learning#4]
How should we do this? I think we need to write some sort of pre-processing file to do this instead of having the Java program do it. We could try his method that was mentioned on Wed (Oct 2).

**Comment by mtwichel** [comment]
I'll take this one as we discussed in class. For review, here's what I'll do:

- Make an Enum **FeatureType** that contains _Categorical_ and _Continuous_
- Make a new class: **Feature**
    - Will contain FeatureType, and two payloads, one double and one String
    - Will have 2 getters
    - Will have to check FeatureType before getting the payload
- Change **Point** to contain a list of **Feature** instead of list of doubles
- Change getEuclidianDistance to getDistance, still inputs two Points, and returns double
    - Will compare like values (categorical to categorical, continuous to continuous)

May need to change the plan in the future, but should be good!

**Comment by mtwichel** [comment]
Ran into a change in my plans. Everything documented above still happened, but I added more:

After reviewing my notes, we do have to do processing on it. Basically we make similarity matrices for each categorical feature, and then we have to pass those matrices in our distance function. Not too big a deal, will chat later
